# Generated by Django 5.2.7 on 2025-12-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broomk", "0006_alter_rooms_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotels",
            name="country",
            field=models.CharField(default="India", max_length=50),
        ),
    ]
