# # Generated by Django 5.2.7 on 2025-12-07 07:13

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ("broomk", "0007_alter_hotels_country"),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name="hotels",
#             name="id",
#             field=models.BigAutoField(primary_key=True, serialize=False),
#         ),
#         migrations.AlterField(
#             model_name="reservation",
#             name="id",
#             field=models.BigAutoField(primary_key=True, serialize=False),
#         ),
#         migrations.AlterField(
#             model_name="rooms",
#             name="id",
#             field=models.BigAutoField(primary_key=True, serialize=False),
#         ),
#     ]

# Generated by Django 5.2.7 on 2025-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broomk", "0007_alter_hotels_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotels",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]

