# Generated by Django 5.2.8 on 2025-12-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomk', '0008_alter_hotels_id_alter_reservation_id_alter_rooms_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='Pakistan', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='Rooms', max_length=40),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'Royal'), ('2', 'delux'), ('3', 'premium')], max_length=50),
        ),
    ]
